version: '3.8'

services:
  backend:
    build:
      context: ./assessment-api
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped

  frontend:
    build:
      context: ./assessment
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - backend
    restart: unless-stopped
